# routes test file (REST Client vscode extention)

@baseUrl = http://localhost:3001

# root
GET {{baseUrl}}/

###
# create user
POST {{baseUrl}}/usuarios
Content-Type: application/json

{
    "username": "samuel",
    "password": "samuel123",
    "name": "Samuel",
    "email": "samuel@email.com"
}

###
# list all users
GET {{baseUrl}}/usuarios

###
# get user by id
GET {{baseUrl}}/usuarios/3



###
# delete user by id
DELETE http://localhost:3001/users/3


###
#  update user by id
PUT http://localhost:3001/users/1
Content-Type: application/json

{
    "name": "Joana",
    "email": "joh@email.com"
}