# routes test file (REST Client vscode extention)

# root
GET http://localhost:3001/

###
# list all users
GET http://localhost:3001/users

###
# get user by id
GET http://localhost:3001/users/4

###
# create user
POST http://localhost:3001/users
Content-Type: application/json

{
    "id": 4,
    "name": "João",
    "email": "joao@email.com"
}

###
# delete user by id
DELETE http://localhost:3001/users/3


###
#  update user by id
PUT http://localhost:3001/users/1
Content-Type: application/json

{
    "name": "Joana",
    "email": "joh@email.com"
}